name: Start API
description: Starts the demo API and waits until it is ready

inputs:
  url:
    description: The URL to run the API on
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        dotnet run --project k6demoapi.csproj --urls "${{ inputs.url }}" &
        sleep 5
      shell: bash

    - run: |
        while ! curl -s "${{ inputs.url }}/health"; do
          echo "Waiting for API..."
          sleep 3
        done
        echo "API is up and running!"
      shell: bash
