name: Build, Performance & Integration Test

on: 
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal

  k6-performance-test:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup K6
      uses: grafana/setup-k6-action@v1

    - name: Start API
      uses: ./.github/actions/start-api  # The action will start the API and wait until it is ready
      with:
        api_url: "http://localhost:5110"              
    
    - name: Run local k6 test
      id: k6
      uses: grafana/run-k6-action@v1
      with:
        path: test/performance/perftest.js
        parallel: true

    - name: Fail Build if K6 Test Fails
      run: |
        echo "K6 Performance Test outcome: ${{ steps.k6.outcome }}"
        if [ ${{ steps.k6.outcome }} != "success" ]; then
          echo "K6 Performance Test failed. Failing the build!"
          exit 1
        fi
  
  integration-test:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Start API
      uses: ./.github/actions/start-api  # The action will start the API and wait until it is ready
      with:
        api_url: "http://localhost:5110"              

    - name: Create test output directory
      run: mkdir -p test-results
    
    - name: Run Integration Tests with Newman
      run: |
        newman run test/integration/k6demoapi.postman_collection.json \
          --reporters cli,junit \
          --reporter-junit-export test-results/newman-report.xml
      